backend:
  name: git-gateway
  branch: feature/netlify-cms
media_folder: "source/images"
public_folder: "/images"
collections:
  - label: "Cadastros"
    name: "cadastros"
    files:
      - label: "Clientes"
        name: "clientes"
        file: "data/clients.yml"
        fields:
          - label: "Registros"
            name: "records"
            widget: "list"
            fields:
              - {label: "Slug", name: "slug", widget: "string"}
              - {label: "Nome", name: "name", widget: "string"}
              - {label: "Logo", name: "logo_url", widget: "image"}
              - {label: "Logo Negativa", name: "logo_negative_url", widget: "image"}
      - label: "Diferenciais"
        name: "differentials"
        file: "data/differentials.yml"
        fields:
          - label: "Registros"
            name: "records"
            widget: "list"
            fields:
              - {label: "Slug", name: "slug", widget: "string"}
              - label: "Título"
                name: "title"
                widget: "object"
                fields:
                  - {label: "Português", name: "pt", widget: "string"}
                  - {label: "Inglês", name: "en", widget: "string"}
                  - {label: "Espanhol", name: "es", widget: "string"}
              - label: "Descrição"
                name: "description"
                widget: "object"
                fields:
                  - {label: "Português", name: "pt", widget: "text"}
                  - {label: "Inglês", name: "en", widget: "text"}
                  - {label: "Espanhol", name: "es", widget: "text"}
              - {label: "Imagem", name: "image_url", widget: "image"}
